# Generated by Django 2.2 on 2021-05-14 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShoeN', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wall_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to='ShoeN.User')),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_name', models.CharField(max_length=45)),
                ('make', models.CharField(max_length=45)),
                ('colaboration', models.CharField(max_length=45)),
                ('release_year', models.DateTimeField(auto_now_add=True)),
                ('color_scheme_1', models.CharField(max_length=45)),
                ('color_scheme_2', models.CharField(max_length=45)),
                ('color_scheme_3', models.CharField(max_length=45)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shoes', to='ShoeN.User')),
            ],
        ),
    ]
