# Generated by Django 2.2 on 2021-05-17 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShoeN', '0005_auto_20210516_0058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wall_Message',
        ),
    ]
