# Generated by Django 2.2 on 2021-05-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoeN', '0016_auto_20210518_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shoe_in',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
