# Generated by Django 2.2 on 2022-06-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoeN', '0019_auto_20210518_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='nike', max_length=255),
        ),
    ]
