# Generated by Django 2.2 on 2021-05-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoeN', '0002_shoe_wall_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall_message',
            name='user_likes',
            field=models.ManyToManyField(related_name='liked_posts', to='ShoeN.User'),
        ),
    ]
