# Generated by Django 2.2 on 2021-05-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoeN', '0003_wall_message_user_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall_message',
            name='shoe_name',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Shoe',
        ),
    ]
