# Generated by Django 2.2 on 2021-05-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoeN', '0014_auto_20210518_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
