# Generated by Django 2.2 on 2021-05-18 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShoeN', '0015_post_header_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='header_image',
            new_name='shoe_image',
        ),
    ]
