# Generated by Django 2.2 on 2021-05-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoeN', '0017_post_shoe_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='colaboration',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
