# Generated by Django 2.2 on 2021-05-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoeN', '0018_post_colaboration'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='color_scheme_1',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='color_scheme_2',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='color_scheme_3',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
