# Generated by Django 2.2 on 2022-06-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoeN', '0023_auto_20220608_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='select_shoe', max_length=255),
        ),
    ]
