# Generated by Django 2.2 on 2022-06-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoeN', '0024_auto_20220609_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='facebook_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='meta_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
