# Generated by Django 2.2 on 2022-06-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoeN', '0028_auto_20220624_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='snapchat_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='soundcloud_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
