# Generated by Django 2.2 on 2022-07-21 17:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShoeN', '0029_auto_20220624_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
    ]
