# Generated by Django 4.1 on 2022-10-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoeN', '0041_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='colaboration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
